import { buildMockBlocks, buildMockReply, streamMockBlocks, streamMockReply } from './mockModel.js';

export class MockProvider {
  constructor() {
    this.name = 'mock';
    this.title = 'Regex Mock Provider';
    this.description = 'Dependency-free provider that streams replies generated by local regex rules.';
  }

  streamResponse({ messages, prompt, enabledSkills, signal, onChunk, onBlock }) {
    const lastPrompt = prompt ?? lastUserPrompt(messages);
    if (typeof onBlock === 'function') {
      return streamMockBlocks({ prompt: lastPrompt, enabledSkills, signal, onChunk, onBlock });
    }
    return streamMockReply({ prompt: lastPrompt, enabledSkills, signal, onChunk });
  }

  complete({ messages, prompt, enabledSkills, structured = false }) {
    const lastPrompt = prompt ?? lastUserPrompt(messages);
    return structured ? buildMockBlocks(lastPrompt, enabledSkills) : buildMockReply(lastPrompt, enabledSkills);
  }
}

export class ReplayProvider {
  constructor() {
    this.name = 'replay';
    this.title = 'Replay Provider';
    this.description = 'Small deterministic provider useful for checking rendering and actions.';
  }

  async streamResponse({ messages, prompt, enabledSkills, signal, onChunk }) {
    const text = [
      'Replay provider response.',
      `Prompt: ${(prompt ?? lastUserPrompt(messages)) || '(empty)'}`,
      `Skills: ${enabledSkills?.join(', ') || 'none'}`,
      'This provider is intentionally simple and deterministic.',
    ].join('\n');

    for (const chunk of text.split(/(\s+)/)) {
      if (signal?.aborted) throw new Error('stream cancelled');
      await new Promise((resolve) => setTimeout(resolve, /^\s+$/.test(chunk) ? 8 : 18));
      if (signal?.aborted) throw new Error('stream cancelled');
      onChunk(chunk);
    }
  }

  complete({ messages, prompt, enabledSkills }) {
    return [
      'Replay provider response.',
      `Prompt: ${(prompt ?? lastUserPrompt(messages)) || '(empty)'}`,
      `Skills: ${enabledSkills?.join(', ') || 'none'}`,
    ].join('\n');
  }
}

const providerFactories = {
  mock: () => new MockProvider(),
  replay: () => new ReplayProvider(),
};

export function createProvider(name = 'mock') {
  const factory = providerFactories[name] ?? providerFactories.mock;
  return factory();
}

export function listProviders() {
  return Object.keys(providerFactories).map((name) => createProvider(name));
}

function lastUserPrompt(messages = []) {
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    if (messages[index].role === 'user') return messages[index].content;
  }
  return '';
}
