const esc = '\u001b';
const st = `${esc}\\`;

export const hostileTerminalFixtures = Object.freeze({
  csiErase: `${esc}[2J`,
  csiCursor: `${esc}[999;999H`,
  privateMode: `${esc}[?1049h`,
  deviceQuery: `${esc}[6n`,
  oscTitleBel: `${esc}]0;hostile title\u0007`,
  oscTitleSt: `${esc}]2;hostile title${st}`,
  oscHyperlink: `${esc}]8;;javascript:alert(1)${st}click${esc}]8;;${st}`,
  osc52Write: `${esc}]52;c;SG9zdGlsZQ==\u0007`,
  osc52Query: `${esc}]52;c;?\u0007`,
  dcs: `${esc}P1;2|hostile${st}`,
  apc: `${esc}_hostile${st}`,
  pm: `${esc}^hostile${st}`,
  sos: `${esc}Xhostile${st}`,
  c1Csi: '\u009b2J',
  c1Osc: '\u009d0;hostile\u009c',
  pointerMarkerGuess: `${esc}[9001;777;80z`,
  malformedCsiU: `${esc}[1114112;1u`,
  oversizedCsiU: `${esc}[${'9'.repeat(512)};${'8'.repeat(512)}u`,
  malformedMouse: `${esc}[<${'9'.repeat(512)};1;1M`,
  incompletePaste: `${esc}[200~${'x'.repeat(256)}`,
  earlyPasteTerminator: `${esc}[200~one${esc}[201~two\r`,
  bidiOverride: 'safe\u202Etxt.exe\u202C',
  bidiIsolate: 'safe\u2066hidden\u2069',
  zeroWidth: 'a\u200Bb\u200Cc\u2060d',
  softHyphen: 'pay\u00ADload',
  invisibleSeparator: 'left\u2063right',
});

export const terminalControlFixtures = Object.freeze([
  hostileTerminalFixtures.csiErase,
  hostileTerminalFixtures.csiCursor,
  hostileTerminalFixtures.privateMode,
  hostileTerminalFixtures.deviceQuery,
  hostileTerminalFixtures.oscTitleBel,
  hostileTerminalFixtures.oscTitleSt,
  hostileTerminalFixtures.oscHyperlink,
  hostileTerminalFixtures.osc52Write,
  hostileTerminalFixtures.osc52Query,
  hostileTerminalFixtures.dcs,
  hostileTerminalFixtures.apc,
  hostileTerminalFixtures.pm,
  hostileTerminalFixtures.sos,
  hostileTerminalFixtures.c1Csi,
  hostileTerminalFixtures.c1Osc,
]);
