export const PULL_REQUESTS = [
  {
    id: 'pr-184',
    number: 184,
    title: 'Stabilize terminal resize and scroll panes',
    author: 'mira',
    branch: 'fix/terminal-resize-scroll',
    base: 'main',
    status: 'Review required',
    checks: '5/6 passing',
    risk: 'medium',
    description: 'This PR replaces several hand-tuned workspace heights with a measured shell layout. It fixes a resize regression where the main pane kept using stale visible rows after the footer or local help grid changed size. The review should verify narrow terminals, tall terminals, scrollback behavior after append, and the interaction between sticky autoscroll and manual page scrolling. The intended UX is close to a normal pull-request review: General explains why the change exists, Commits shows the changed files, Diff exposes the patch for the selected commit, and Comments behaves like a live review thread.',
    commits: [
      {
        sha: '8f12c7e',
        title: 'Measure workspace chrome before rendering main panes',
        author: 'mira',
        files: ['src/lib/ui/workspace.js', 'src/lib/ui/layout/index.js', 'test/uiComponents.test.js'],
        diff: [
          'diff --git a/src/lib/ui/workspace.js b/src/lib/ui/workspace.js',
          '@@ -68,16 +68,32 @@ export function WorkspaceShell({ title, subtitle, stats, tabs, main, activity, height }) {',
          '- const mainHeight = height - 14;',
          '- const header = WorkspaceHeader({ title, subtitle, stats });',
          '- const tabBar = WorkspaceTabs({ tabs, activeTab });',
          '- return Column(header, tabBar, Box({ height: mainHeight }, main), activity);',
          '+ const layout = resolveWorkspaceShellLayout({',
          '+   width, height, title, subtitle, stats, right, tabs, activeTab,',
          '+   tabHint, command, footer, activity, theme, minMainHeight,',
          '+ });',
          '+ const header = WorkspaceHeader({ title, subtitle, stats, right, theme });',
          '+ const tabBar = WorkspaceTabs({ tabs, activeTab, hint: tabHint, theme });',
          '+ return Column(',
          '+   header,',
          '+   tabBar,',
          '+   Box({ height: layout.mainHeight }, main),',
          '+   activity,',
          '+ );',
          '+}',
          '+',
          '+export function resolveWorkspaceShellLayout({ height, stats = [], tabs = [], activity = null, command = null, footer = null, minMainHeight = 6 }) {',
          '+  const chrome = measureWorkspaceChrome({ stats, tabs, activity, command, footer });',
          '+  return { mainHeight: Math.max(minMainHeight, Number(height) - chrome) };',
          '+}',
          '',
          'diff --git a/src/lib/ui/layout/index.js b/src/lib/ui/layout/index.js',
          '@@ -120,11 +120,23 @@ export function measureNodeHeight(node, width) {',
          '- if (!node) return 0;',
          '- const frame = layout(node, { width });',
          '- return frame.lines.length;',
          '+ if (!node) return 0;',
          '+ const frame = layout(node, { width, height: Number.POSITIVE_INFINITY });',
          '+ return frame.lines.length;',
          '+}',
          '+',
          '+export function measureStackHeight(nodes, width) {',
          '+  return nodes.reduce((total, node) => {',
          '+    if (!node) return total;',
          '+    return total + measureNodeHeight(node, width);',
          '+  }, 0);',
          ' ',
          ' export function clampFrameHeight(frame, height) {',
          '+  if (!Number.isFinite(height)) return frame;',
          '   return { ...frame, lines: frame.lines.slice(0, height) };',
          ' }',
          '',
          'diff --git a/test/uiComponents.test.js b/test/uiComponents.test.js',
          '@@ -42,6 +42,20 @@ test(\'workspace tabs render active item\', () => {',
          '+test(\'workspace layout measures bordered help grids\', () => {',
          '+  const activity = KeyHintBar({ title: \' LOCAL HELP \', hints: [[\'Tab\', \'focus\'], [\'Ctrl+O\', \'open\']], gridBorder: true });',
          '+  const result = resolveWorkspaceShellLayout({',
          '+    width: 100,',
          '+    height: 24,',
          '+    tabs: [{ id: \'general\', label: \'General\' }],',
          '+    activity,',
          '+    minMainHeight: 8,',
          '+  });',
          '+  assert.equal(result.mainHeight, 10);',
          '+});',
          '+',
          ' test(\'workspace pane keeps title visible\', () => {',
        ],
      },
      {
        sha: 'c02fd91',
        title: 'Keep read-only transcript scroll anchored at bottom',
        author: 'mira',
        files: ['src/lib/scrollState.js', 'examples/streaming-workbench.js', 'test/examples.test.js'],
        diff: [
          'diff --git a/src/lib/scrollState.js b/src/lib/scrollState.js',
          '@@ -1,11 +1,30 @@',
          '+export function resolveAutoScrollOffset({ scroll, totalRows, previousTotalRows, visibleRows, sticky }) {',
          '+  const previousMax = scrollMax(previousTotalRows, visibleRows);',
          '+  const nextMax = scrollMax(totalRows, visibleRows);',
          '+  if (sticky === true) return nextMax;',
          '+  if (sticky === false) return clampScrollOffset(scroll, nextMax);',
          '+  return scroll >= previousMax ? nextMax : clampScrollOffset(scroll, nextMax);',
          '+}',
          '+',
          ' export function scrollMax(totalRows, visibleRows) {',
          '-  return Math.max(0, totalRows - visibleRows);',
          '+  return Math.max(0, Number(totalRows) - Math.max(1, Number(visibleRows)));',
          ' }',
          '',
          'diff --git a/examples/streaming-workbench.js b/examples/streaming-workbench.js',
          '@@ -188,12 +188,26 @@ function transcriptPane(state, width, height) {',
          '- state.transcriptScroll = scrollMax(lines.length, visibleRows);',
          '+ state.transcriptScroll = resolveAutoScrollOffset({',
          '+   scroll: state.transcriptScroll,',
          '+   totalRows: lines.length,',
          '+   previousTotalRows: state.transcriptMetrics.totalRows,',
          '+   visibleRows,',
          '+   sticky: state.transcriptSticky,',
          '+ });',
          '+ state.transcriptMetrics = { totalRows: lines.length, visibleRows };',
          '+ state.transcriptSticky = state.transcriptScroll >= scrollMax(lines.length, visibleRows);',
          '  return ScrollPane({ lines, height, scroll: state.transcriptScroll });',
          '}',
          '',
          'diff --git a/test/examples.test.js b/test/examples.test.js',
          '@@ -88,6 +88,18 @@ test(\'streaming workbench appends chunks\', () => {',
          '+test(\'streaming workbench preserves manual scrollback\', () => {',
          '+  const state = createStreamingWorkbenchState();',
          '+  state.transcriptScroll = 0;',
          '+  state.transcriptSticky = false;',
          '+  appendStreamingChunk(state, \'late chunk\');',
          '+  createStreamingWorkbenchView({ state, width: 110, height: 24 });',
          '+  assert.equal(state.transcriptScroll, 0);',
          '+});',
        ],
      },
      {
        sha: 'f91aa73',
        title: 'Route scroll keys through pane-specific metrics',
        author: 'mira',
        files: ['examples/code-review.js', 'examples/_workspaceExampleUtils.js', 'test/examplesAdvanced.test.js'],
        diff: [
          'diff --git a/examples/code-review.js b/examples/code-review.js',
          '@@ -420,14 +420,31 @@ function scrollablePane({ title, pane, state, lines, width, height }) {',
          '- const visibleRows = height - 4;',
          '- state.paneScroll[pane] = Math.min(state.paneScroll[pane], scrollMax(lines.length, visibleRows));',
          '+ const visibleRows = Math.max(1, Number(height) - 4);',
          '+ const metrics = state.scrollMetrics[pane] ?? { totalRows: 0, visibleRows };',
          '+ const result = resolveScrollKeyOffset({',
          '+   keyName: \'noop\',',
          '+   scroll: state.paneScroll[pane] ?? 0,',
          '+   totalRows: lines.length,',
          '+   visibleRows,',
          '+   previousTotalRows: metrics.totalRows,',
          '+ });',
          '+ state.paneScroll[pane] = result.scroll;',
          '+ state.scrollMetrics[pane] = { totalRows: lines.length, visibleRows };',
          '  return WorkspacePane({ title, height, children: [',
          '    ScrollPane({ lines, height: height - 2, scroll: state.paneScroll[pane] }),',
          '  ]});',
          '}',
          '',
          'diff --git a/examples/_workspaceExampleUtils.js b/examples/_workspaceExampleUtils.js',
          '@@ -10,6 +10,16 @@ export function responsiveTabHint(prefix, tabs, visibleTabs) {',
          '+export function routeScrollKey(state, pane, keyName) {',
          '+  const metrics = state.scrollMetrics[pane] ?? { totalRows: 0, visibleRows: 1 };',
          '+  return resolveScrollKeyOffset({',
          '+    keyName,',
          '+    scroll: state.paneScroll[pane] ?? 0,',
          '+    totalRows: metrics.totalRows,',
          '+    visibleRows: metrics.visibleRows,',
          '+  });',
          '+}',
          '+',
          ' export function cycleTab(state, tabs, direction) {',
          '',
          'diff --git a/test/examplesAdvanced.test.js b/test/examplesAdvanced.test.js',
          '@@ -92,6 +92,19 @@ test(\'code review workspace uses read-only PR details\', () => {',
          '+test(\'code review scroll keys use current pane metrics\', () => {',
          '+  const state = createCodeReviewState();',
          '+  handleCodeReviewKey({ key: { name: \'enter\' }, state });',
          '+  state.activeTab = \'general\';',
          '+  createCodeReviewView({ state, width: 90, height: 18 });',
          '+  handleCodeReviewKey({ key: { name: \'page-down\' }, state });',
          '+  assert.ok(state.paneScroll.general > 0);',
          '+});',
        ],
      },
    ],
    comments: [
      { author: 'alex', location: 'src/lib/ui/workspace.js:76', body: 'Good direction. Please add a regression for very small terminal height so the pane border is still visible. I would also like the review to cover the case where the footer is absent but the help grid is still present, because that is where fixed subtraction usually drifts first.', status: 'open' },
      { author: 'review-bot', location: 'src/lib/scrollState.js:41', body: 'The sticky expression is much clearer now, but the helper still mixes absolute row counts and previous totals. Please add a test where the previous transcript has fewer rows than the visible window, then receives enough chunks to overflow.', status: 'open' },
      { author: 'mira', location: 'examples/streaming-workbench.js:192', body: 'Added a transcript test that scrolls up, appends a chunk, then returns to bottom. I also verified that the footer and local help grid no longer change the maximum scroll value after resize.', status: 'resolved' },
      { author: 'sam', location: 'src/lib/ui/layout/index.js:129', body: 'One concern: measuring with an unbounded height should not mask components that intentionally clamp themselves. It may be worth documenting which components are safe to measure this way, otherwise future widgets could report a misleading height.', status: 'open' },
      { author: 'alex', location: 'test/uiComponents.test.js:51', body: 'The assertion is helpful, but please include the rendered frame in the failure message or split expected chrome calculation into named values. When this fails during a resize regression, a single expected number will be difficult to diagnose.', status: 'open' },
      { author: 'mira', location: 'examples/code-review.js:430', body: 'I updated the code-review fixture to keep one diff section per listed file. This should make the Commits tab and Diff tab feel consistent during manual review.', status: 'resolved' },
    ],
  },
  {
    id: 'pr-207',
    number: 207,
    title: 'Add command palette accepted-action history',
    author: 'denis',
    branch: 'feat/palette-accepted-log',
    base: 'main',
    status: 'Changes requested',
    checks: '4/4 passing',
    risk: 'low',
    description: 'Adds an Accepted tab to the command palette example and records the last accepted actions. The goal is to make palette demos feel more like a real product surface: users can search, inspect details, accept an action, then review what happened. The implementation should keep Details read-only and avoid hidden state changes while another tab is active. Please pay attention to keyboard routing, scroll metrics in the accepted log, and whether the rendered empty state remains stable on small terminals.',
    commits: [
      {
        sha: '3e9cbe4',
        title: 'Record accepted palette actions',
        author: 'denis',
        files: ['examples/command-palette.js', 'test/examples.test.js', 'docs/examples.md'],
        diff: [
          'diff --git a/examples/command-palette.js b/examples/command-palette.js',
          '@@ -210,11 +210,30 @@ function acceptSelectedAction(state) {',
          '+ state.accepted.unshift({',
          '+   id: selected.id,',
          '+   title: selected.title,',
          '+   group: selected.group,',
          '+   at: new Date().toISOString(),',
          '+ });',
          '+ if (state.accepted.length > 20) state.accepted = state.accepted.slice(0, 20);',
          '- state.activeTab = \'details\';',
          '+ state.activeTab = \'accepted\';',
          '+ state.acceptedSelectedIndex = 0;',
          '+ state.status = `Accepted ${selected.title}.`;',
          '+ state.toast = { level: \'success\', message: `Accepted ${selected.title}.` };',
          '}',
          '',
          'diff --git a/test/examples.test.js b/test/examples.test.js',
          '@@ -132,6 +132,19 @@ test(\'command palette accepts selected action\', () => {',
          '+test(\'command palette records accepted action history\', () => {',
          '+  const state = createCommandPaletteState();',
          '+  handleCommandPaletteKey({ key: { name: \'enter\' }, state });',
          '+  assert.equal(state.accepted.length, 1);',
          '+  assert.equal(state.activeTab, \'accepted\');',
          '+  assert.match(state.accepted[0].title, /Open|Create|Toggle/);',
          '+});',
          '',
          'diff --git a/docs/examples.md b/docs/examples.md',
          '@@ -40,7 +40,9 @@ npm run example:palette',
          '-A searchable command launcher with selected-action details.',
          '+A searchable command launcher with selected-action details, accepted-action history,',
          '+tab-scoped keyboard handling, and a stable empty state for narrow terminals.',
        ],
      },
      {
        sha: '55d72aa',
        title: 'Bound accepted log selection to active tab',
        author: 'denis',
        files: ['examples/command-palette.js', 'src/lib/focusManager.js', 'test/examplesAdvanced.test.js'],
        diff: [
          'diff --git a/examples/command-palette.js b/examples/command-palette.js',
          '@@ -318,11 +318,24 @@ function handlePaletteNavigation(key, state) {',
          '- if (key.name === \'down\') moveAcceptedSelection(state, 1);',
          '+ if (state.activeTab === \'accepted\' && key.name === \'down\') {',
          '+   moveAcceptedSelection(state, 1);',
          '+   return;',
          '+ }',
          '+ if (state.activeTab === \'accepted\' && key.name === \'up\') {',
          '+   moveAcceptedSelection(state, -1);',
          '+   return;',
          '+ }',
          '+ if (state.activeTab !== \'accepted\' && (key.name === \'up\' || key.name === \'down\')) {',
          '+   moveActionSelection(state, key.name === \'down\' ? 1 : -1);',
          '+   return;',
          '+ }',
          '',
          'diff --git a/src/lib/focusManager.js b/src/lib/focusManager.js',
          '@@ -52,7 +52,14 @@ export class FocusManager {',
          '+  has(id) {',
          '+    return this.order.includes(id);',
          '+  }',
          '+',
          '+  currentOr(defaultId) {',
          '+    return this.has(this.current()) ? this.current() : defaultId;',
          '+  }',
          '',
          'diff --git a/test/examplesAdvanced.test.js b/test/examplesAdvanced.test.js',
          '@@ -146,6 +146,17 @@ test(\'command palette renders accepted log\', () => {',
          '+test(\'accepted history navigation is tab scoped\', () => {',
          '+  const state = createCommandPaletteState();',
          '+  state.activeTab = \'details\';',
          '+  handleCommandPaletteKey({ key: { name: \'down\' }, state });',
          '+  assert.equal(state.acceptedSelectedIndex, 0);',
          '+});',
        ],
      },
      {
        sha: '729ab5d',
        title: 'Render empty accepted state without layout jump',
        author: 'denis',
        files: ['examples/command-palette.js', 'examples/_workspaceExampleUtils.js', 'test/uiComponents.test.js'],
        diff: [
          'diff --git a/examples/command-palette.js b/examples/command-palette.js',
          '@@ -384,9 +384,24 @@ function acceptedPane(state, width, height) {',
          '- if (!state.accepted.length) return Text(\'No accepted actions yet.\');',
          '+ const rows = state.accepted.length',
          '+   ? acceptedRows(state, width)',
          '+   : emptyAcceptedRows(width);',
          '+ return WorkspacePane({',
          '+   title: \' ACCEPTED ACTIONS \',',
          '+   active: state.activeTab === \'accepted\',',
          '+   height,',
          '+   children: [ScrollPane({ lines: rows, width, height: height - 2, scroll: state.acceptedScroll })],',
          '+ });',
          '+}',
          '',
          'diff --git a/examples/_workspaceExampleUtils.js b/examples/_workspaceExampleUtils.js',
          '@@ -30,6 +30,13 @@ export function responsiveTabs(tabs, active, width, options = {}) {',
          '+export function emptyStateRows(title, body) {',
          '+  return [',
          '+    `No ${title} yet.`,',
          '+    body,',
          '+    \'Use Enter on an action to create the first entry.\',',
          '+  ];',
          '+}',
          '',
          'diff --git a/test/uiComponents.test.js b/test/uiComponents.test.js',
          '@@ -73,6 +73,14 @@ test(\'scroll pane clamps offsets\', () => {',
          '+test(\'empty accepted state keeps pane height stable\', () => {',
          '+  const state = createCommandPaletteState();',
          '+  const output = renderToString(createCommandPaletteView({ state, width: 80, height: 22 }), { width: 80, height: 22 });',
          '+  assert.match(stripAnsi(output), /No accepted actions yet/);',
          '+});',
        ],
      },
    ],
    comments: [
      { author: 'alex', location: 'examples/command-palette.js:246', body: 'This should use the same tab-scoped keyboard model as editor and stream. Right now the selection behavior is close, but the review should explicitly cover what happens when Details is active and the accepted log already contains several actions.', status: 'open' },
      { author: 'denis', location: 'test/examples.test.js:118', body: 'Added a test for accepted action navigation. I also included an empty-state check because the previous implementation changed height as soon as the first action was accepted.', status: 'resolved' },
      { author: 'review-bot', location: 'examples/command-palette.js:390', body: 'The toast message is useful, but please make sure it does not steal vertical space from the main pane without recalculating the pane height. We have seen this class of issue in workspace examples before.', status: 'open' },
      { author: 'nora', location: 'docs/examples.md:44', body: 'The docs update is okay, but avoid introducing another hierarchy that competes with the examples index. The output of npm run examples should be the canonical grouped list.', status: 'open' },
      { author: 'alex', location: 'src/lib/focusManager.js:54', body: 'This helper might be useful, but it is not used outside this example. Either use it in another focus-managed example or keep the change local to avoid expanding the public surface too early.', status: 'open' },
    ],
  },
  {
    id: 'pr-231',
    number: 231,
    title: 'Refactor input editor newline handling',
    author: 'kai',
    branch: 'refactor/input-editor-newline',
    base: 'main',
    status: 'Draft',
    checks: '2/3 passing',
    risk: 'high',
    description: 'Unifies Ctrl+J, Ctrl+Enter and paste handling for multiline editors. The refactor touches key parsing, editor mutation and several interactive examples, so the review should focus on regressions around macOS escape sequences, Backspace versus Delete, cursor movement at wrapped lines, and multiline comment composition. This is intentionally a larger PR for the example: there is enough text, enough commits, and enough comments to exercise scrolling in every central pane.',
    commits: [
      {
        sha: 'a91b0c2',
        title: 'Normalize newline shortcuts in key parser',
        author: 'kai',
        files: ['src/lib/keyParser.js', 'test/keyParser.test.js', 'docs/interactive-apps.md'],
        diff: [
          'diff --git a/src/lib/keyParser.js b/src/lib/keyParser.js',
          '@@ -92,12 +92,34 @@ export function parseKey(input) {',
          '+ if (input === \'\\n\') return { name: \'ctrl-j\', ctrl: true, sequence: input };',
          '+ if (sequence === \'\\x1b[13;5u\') return { name: \'enter\', ctrl: true, sequence };',
          '+ if (sequence === \'\\x1b[111;5u\') return { name: \'o\', ctrl: true, sequence };',
          '- if (input === \'\\r\') return { name: \'enter\' };',
          '+ if (input === \'\\r\') return { name: \'enter\', sequence: input };',
          '+ const csi = parseCsiU(sequence);',
          '+ if (csi) return csi;',
          '',
          'diff --git a/test/keyParser.test.js b/test/keyParser.test.js',
          '@@ -35,6 +35,20 @@ test(\'parseKey normalizes arrows\', () => {',
          '+test(\'parseKey normalizes ctrl enter and ctrl o CSI-u sequences\', () => {',
          '+  assert.deepEqual(parseKey(\'\\x1b[13;5u\'), { name: \'enter\', ctrl: true, sequence: \'\\x1b[13;5u\' });',
          '+  assert.equal(parseKey(\'\\x1b[111;5u\').name, \'o\');',
          '+  assert.equal(parseKey(\'\\x1b[111;5u\').ctrl, true);',
          '+});',
          '+',
          '+test(\'parseKey keeps macOS backspace distinct from delete\', () => {',
          '+  assert.equal(parseKey(\'\\x7f\').name, \'backspace\');',
          '+  assert.equal(parseKey(\'\\x1b[3~\').name, \'delete\');',
          '+});',
          '',
          'diff --git a/docs/interactive-apps.md b/docs/interactive-apps.md',
          '@@ -64,6 +64,12 @@ Multiline editors usually handle Ctrl+J manually.',
          '+When a terminal emits CSI-u sequences, parseKey normalizes Ctrl+Enter and Ctrl+O',
          '+to the same key objects as classic control bytes. This keeps examples portable',
          '+between default Terminal.app, iTerm2, and modern terminal emulators.',
        ],
      },
      {
        sha: '4f5ac20',
        title: 'Use multiline editor helpers in examples',
        author: 'kai',
        files: ['examples/editor-lab.js', 'examples/streaming-workbench.js', 'examples/code-review.js'],
        diff: [
          'diff --git a/examples/editor-lab.js b/examples/editor-lab.js',
          '@@ -242,10 +242,24 @@ function handleDraftEditorKey(key, state) {',
          '- if (key.name === \'enter\' && key.ctrl) editor.insertLineBreak();',
          '+ if (isEditorNewlineKey(key)) {',
          '+   editor.insertLineBreak();',
          '+   state.status = \'Inserted newline in draft.\';',
          '+   return;',
          '+ }',
          '',
          'diff --git a/examples/streaming-workbench.js b/examples/streaming-workbench.js',
          '@@ -352,8 +352,22 @@ function handlePromptKey(key, state) {',
          '- if (key.name === \'ctrl-j\') state.promptEditor.insertLineBreak();',
          '+ if (isEditorNewlineKey(key)) {',
          '+   state.promptEditor.insertLineBreak();',
          '+   state.status = \'Inserted multiline prompt break.\';',
          '+   return;',
          '+ }',
          '+ editInput(state.promptEditor, key, state, \'prompt\');',
          '',
          'diff --git a/examples/code-review.js b/examples/code-review.js',
          '@@ -736,9 +736,21 @@ function handleCommentEditorKey(key, state) {',
          '- if (key.name === \'ctrl-j\') state.commentEditor.insertLineBreak();',
          '+ if (isEditorNewlineKey(key)) {',
          '+   state.commentEditor.insertLineBreak();',
          '+   state.commentsSticky = true;',
          '+   state.status = \'Inserted a new line in the comment.\';',
          '+   return;',
          '+ }',
        ],
      },
      {
        sha: '6bdbd32',
        title: 'Add regression coverage for comment composer navigation',
        author: 'kai',
        files: ['test/examplesAdvanced.test.js', 'examples/code-review.js', 'src/lib/inputEditor.js'],
        diff: [
          'diff --git a/test/examplesAdvanced.test.js b/test/examplesAdvanced.test.js',
          '@@ -112,6 +112,22 @@ test(\'code review workspace uses read-only PR details\', () => {',
          '+test(\'code review composer accepts multiline comments\', () => {',
          '+  const state = createCodeReviewState();',
          '+  handleCodeReviewKey({ key: { name: \'enter\' }, state });',
          '+  state.activeTab = \'comments\';',
          '+  handleCodeReviewKey({ key: { name: \'n\' }, state });',
          '+  for (const ch of \'line one\') handleCodeReviewKey({ key: { name: ch, printable: true, text: ch }, state });',
          '+  handleCodeReviewKey({ key: { name: \'ctrl-j\', ctrl: true }, state });',
          '+  for (const ch of \'line two\') handleCodeReviewKey({ key: { name: ch, printable: true, text: ch }, state });',
          '+  assert.match(state.commentEditor.value, /line one\\nline two/);',
          '+});',
          '',
          'diff --git a/examples/code-review.js b/examples/code-review.js',
          '@@ -480,7 +480,17 @@ function commentThreadLayout(state, width) {',
          '+lines.push(\'┌─ New review comment\');',
          '+for (const line of editorLines) lines.push(`│ ${line}`);',
          '+lines.push(\'└──────────────────────\');',
          '+state.commentsSticky = true;',
          '',
          'diff --git a/src/lib/inputEditor.js b/src/lib/inputEditor.js',
          '@@ -180,8 +180,19 @@ export class InputEditor {',
          '+moveVertical(delta) {',
          '+  const current = this.positionToLineColumn(this.cursor);',
          '+  const targetLine = clamp(current.line + delta, 0, this.lineCount() - 1);',
          '+  this.cursor = this.lineColumnToPosition(targetLine, current.column);',
          '+}',
        ],
      },
    ],
    comments: [
      { author: 'alex', location: 'src/lib/keyParser.js:52', body: 'Please verify Backspace on macOS. We broke it once while normalizing escape sequences, and it was especially confusing because Backspace started behaving like Delete in the middle of editing a comment.', status: 'open' },
      { author: 'review-bot', location: 'examples/code-review.js:311', body: 'The refactor changes code-review behavior. Please keep an example-level regression test that opens the comment composer, inserts multiline text, confirms posting, and verifies that the comments pane autoscrolls to the new block.', status: 'open' },
      { author: 'kai', location: 'examples/editor-lab.js:244', body: 'I reused the same helper in editor, stream and code-review. The intent is that terminal-specific newline sequences are normalized once and all examples consume the same semantic key.', status: 'open' },
      { author: 'alex', location: 'test/keyParser.test.js:39', body: 'The Ctrl+O regression coverage matters for the code-review picker. Please keep the test close to the parser, but also verify the example-level shortcut because users usually notice the broken modal before they inspect normalized key objects.', status: 'open' },
      { author: 'mira', location: 'docs/interactive-apps.md:69', body: 'This docs note is useful, but avoid implying that every terminal emits CSI-u by default. The wording should say the parser handles it when it appears, not that users should configure it.', status: 'resolved' },
      { author: 'review-bot', location: 'src/lib/inputEditor.js:184', body: 'Vertical movement should preserve the preferred column when moving across shorter wrapped lines. This implementation is acceptable for logical lines, but the review should call out that visual wrapping is handled at render time.', status: 'open' },
    ],
  },
];

export const LIVE_COMMENT_TEMPLATES = [
  {
    author: 'review-bot',
    status: 'open',
    body: 'New automated review note: this hunk changed after the first pass. Please re-check the surrounding tests and confirm the behavior still matches the PR description before approving.',
  },
  {
    author: 'sam',
    status: 'open',
    body: 'I just reproduced this path locally. The behavior looks correct, but the comment thread should keep enough context around the changed file so later reviewers do not have to reopen the whole diff.',
  },
  {
    author: 'mira',
    status: 'resolved',
    body: 'Pushed a follow-up that addresses the previous concern. Leaving this note in the thread so the review example can show a resolved live update next to open comments.',
  },
  {
    author: 'alex',
    status: 'open',
    body: 'One more edge case appeared while testing scrollback: when a comment arrives while the reviewer is reading older comments, the pane should not steal focus. A toast with a jump action is the right model here.',
  },
  {
    author: 'nora',
    status: 'open',
    body: 'This is a small copy note, but the wording in the changed area should stay consistent with the rest of the workspace examples. Please avoid adding another naming scheme in the README.',
  },
];

export function createInitialLiveDelay() {
  return 6 + Math.floor(Math.random() * 5);
}

export function createNextLiveDelay(state) {
  const emitted = Math.max(0, Number(state?.liveCommentCursor ?? 0));
  const base = 12 + emitted * 3;
  return Math.min(36, base + Math.floor(Math.random() * 8));
}
